In [3]:
#NumPy - Numerical Python 
#It is used for the computational purpose (mathematical & logical operations) of multidimensional arrays.
#Numarray - additional functionalities

In [4]:
 import numpy as np

In [5]:
#creating an array
#ndarray - stores the data continuously in the memory either row major order or column major order.
#python array - blocks ->address -->data
#ndarray - data
a = np.array ([1,2])
print(a)
print(type(a))

[1 2]
<class 'numpy.ndarray'>


In [6]:
#row major order - 1,2,3,4
#column major order - 1,3,2,4
b = np.array ([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [7]:
c=np.array ([1,2,3], dtype=float)
print(c)

[1. 2. 3.]


In [8]:
#array attributes

#ndim - number of axes
print(b.ndim)
#shape - it returns the dimensions in tuple
print(b.shape)

2
(2, 2)


In [9]:
#reshape
d= np.array([[1,2],[4,5],[6,7]])
print(d.shape)
print(d.reshape(2,3))

(3, 2)
[[1 2 4]
 [5 6 7]]


In [10]:
a= np.arange (20)
print(a.reshape(2,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [11]:
a= np.arange(20, 30 , 2) #it will return evenly spaced values excluding end point
print(a)

[20 22 24 26 28]


In [12]:
b= np.linspace(1, 4, 9) #it will return evenly spaced values incuding the end point
print(b)

[1.    1.375 1.75  2.125 2.5   2.875 3.25  3.625 4.   ]


In [13]:
print(d.shape)
print(d.reshape(2,3))
print(d) #reshape doesn't affect the original array, it returns a newly created array
print(d.shape)
d.resize(2,3) #resize affects the original array
print(d)

(3, 2)
[[1 2 4]
 [5 6 7]]
[[1 2]
 [4 5]
 [6 7]]
(3, 2)
[[1 2 4]
 [5 6 7]]


In [14]:
print(np.ones((3,2), dtype=int))
print(np.zeros ((2,3), dtype=int))
print(np.eye(3))
print(np.diag(d)) #extracts the diagonal elements and creates an array

[[1 1]
 [1 1]
 [1 1]]
[[0 0 0]
 [0 0 0]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 6]


In [15]:
a = np.arange(3,10,2).reshape(2,2)
print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))
print(np.std(a))
print(np.mean(a))
print(np.sum(a))
print(np.sin(a))

[[1.73205081 2.23606798]
 [2.64575131 3.        ]]
[[1.09861229 1.60943791]
 [1.94591015 2.19722458]]
[[  20.08553692  148.4131591 ]
 [1096.63315843 8103.08392758]]
2.23606797749979
6.0
24
[[ 0.14112001 -0.95892427]
 [ 0.6569866   0.41211849]]


In [16]:
#Slicing

a= np.arange(0,20).reshape(4,5)

print(a)
print (a[1,2])
print (a [0, 2:5])
print (a[ 0:2, 2:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
7
[2 3 4]
[[2 3]
 [7 8]]


In [37]:
#Arithmetic operations on Numpy

a= np.arange(0,20).reshape(4,5)
b= np.arange(20,40).reshape(4,5)

print(a+b)
print(a-b)
print(a/b)
print(a*b)



[[20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]]
[[-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]]
[[0.         0.04761905 0.09090909 0.13043478 0.16666667]
 [0.2        0.23076923 0.25925926 0.28571429 0.31034483]
 [0.33333333 0.35483871 0.375      0.39393939 0.41176471]
 [0.42857143 0.44444444 0.45945946 0.47368421 0.48717949]]
[[  0  21  44  69  96]
 [125 156 189 224 261]
 [300 341 384 429 476]
 [525 576 629 684 741]]


In [48]:
a= np.linspace(0,20,8).reshape(4,2)
print(np.round_(a, decimals= 3))

[[ 0.     2.857]
 [ 5.714  8.571]
 [11.429 14.286]
 [17.143 20.   ]]


Object `np.round_` not found.
